name: DTVJob
version: '${project.version}'
main: dataverse.dtvjob.DTVJob
api-version: '1.16'
authors: [Matyha Shatalov,DataVerse Team]
commands:
  dtvjob:
    description: информация о плагине
    usage: /dtvjob